
all: cesar-k-key freq-count

cesar-k-key:
	gcc -c cesar-k-key.c
	gcc cesar-k-key.o -o cesar-k-key

freq-count:
	gcc -c freq-count.c 
	gcc freq-count.o -o freq-count

clean:
	rm -f cesar-k-key freq-count *.o

